name: Deploy ws-server to Cloud Run

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cloud-run/ws-server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/872666885870/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deployer@ai-yokocho.iam.gserviceaccount.com"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "ws-server"
          region: "asia-northeast1"
          source: "./cloud-run/ws-server"
